Repository dinesh-2047/Qrexel, pull requests merged in 2025-03, with the labels that each got.

#33 loading animation added
  package-lock.json
  package.json
  public/infinite-spinner.svg
  src/App.tsx
  src/pages/Loader.tsx
Labels: medium, jwoc

#38 Responsive footer is added
  .hintrc
  src/App.tsx
  src/components/Footer.tsx
Labels: easy, jwoc

#41 Feature/responsiveness
  package-lock.json
  package.json
  src/App.tsx
  src/components/Navbar.tsx
  src/components/ui/QrCodes .tsx
  src/pages/Home.tsx
  src/pages/NotFound.tsx
  src/pages/Scanner.tsx
Labels: hard, jwoc

#49 Feature/dark mode
  index.html
  src/App.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/ui/QrCodes .tsx
  src/contexts/Themeprovider.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Scanner.tsx
  src/pages/SignUp.tsx
Labels: medium, jwoc

#50 Adding custom cursour with added assets
  index.html
  public/cursours/icons8-3d-pointer-48.png
  public/cursours/icons8-3d-pointer.gif
  public/cursours/icons8-hand-cursor-30.png
  public/cursours/icons8-hand-cursor-50.png
  public/cursours/icons8-select-cursor-24.png
  public/cursours/icons8-select-cursor-30.png
  public/cursours/icons8-select-cursor-48.png
  public/favicon/site.webmanifest
  src/index.css
  tailwind.config.js
Labels: medium, jwoc

#53 fully responsive
  src/pages/Home.tsx
Labels: medium, jwoc

#54 Feature/hero section
  .hintrc
  src/App.tsx
  src/components/Hero.tsx
  src/pages/Home.tsx
  tailwind.config.js
Labels: hard, jwoc
