Repository dinesh-2047/Qrexel, pull requests merged in 2025-02, with the labels that each got.

#3 DarkMode feature added
  src/App.tsx
  src/components/DarkMode.tsx
  src/components/Navbar.tsx
  src/pages/Home.tsx
  src/utils/moon.png
  src/utils/sun.png
  tailwind.config.js
Labels: medium, jwoc

#12 Scanner
  src/pages/Scanner.tsx
Labels: hard, jwoc

#20 removed extra button
  src/App.tsx
Labels: easy, jwoc

#21 About QR codes
  qr.png
  qr1.png
  qr2.png
  qr3.png
  src/App.tsx
  src/components/ui/QrCodes .tsx
  src/pages/Home.tsx
Labels: medium, jwoc

#23 Added Favicon
  index.html
  src/utils/favicon.png
Labels: medium, jwoc

#26 Authentication added
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/firebase/config.ts
  src/main.tsx
  src/pages/Auth.tsx
  src/pages/Dashboard.tsx
  src/pages/Home.tsx
  src/store/useStore.ts
  src/supabase/client.ts
Labels: hard, jwoc
